### ISSUE TITLE
chart.min.js reference invalid

### ISSUE THREAD

**Issue by shikingram** [Shen-Yu/hugo-chart#3]
I don't know if anyone still maintains this project, but this url has expired

https://github.com/shen-yu/hugo-chart/blob/32cef4e86d23e8fffdb5f35f12995864fbff92d7/layouts/shortcodes/chart.html#L9

**Comment by shikingram** [comment]
#4

**Comment by shen-yu** [comment]
@shikingram Thanks, i'v merged this PR.
