### ISSUE TITLE
Uncaught ReferenceError: Chart is not defined

### ISSUE THREAD

**Issue by 2niuhe** [Shen-Yu/hugo-chart#7]
I think this is a ChartJS problem

https://github.com/shen-yu/hugo-chart/blob/618a11d698590cb3f7a9d6b5db088a033b2c14c6/layouts/shortcodes/chart.html#L10

I fix the problem by changing the `chart.min.js` to `Chart.min.js`

**Comment by agilob** [comment]
thanks for posting your solution in here :+1:

**Comment by AdamFermier** [comment]
Great - that worked for me - thanks so much!  I've added in a pull request https://github.com/shen-yu/hugo-chart/pull/10
